# Generated by Django 5.2.7 on 2025-12-18 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('part_type', models.CharField(choices=[('head', 'Голова'), ('body', 'Туловище')], max_length=10, verbose_name='Тип')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('image', models.ImageField(upload_to='cat_parts/', verbose_name='Изображение')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Часть кота',
                'verbose_name_plural': 'Части котов',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Фамилия')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Баланс')),
                ('owned_parts', models.ManyToManyField(blank=True, to='auth_app.catpart', verbose_name='Купленные части')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя кота')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('sent_to_email', models.BooleanField(default=False, verbose_name='Отправлен на почту')),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cats_as_body', to='auth_app.catpart', verbose_name='Туловище')),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cats_as_head', to='auth_app.catpart', verbose_name='Голова')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cats', to='auth_app.profile', verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Кот',
                'verbose_name_plural': 'Коты',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.catpart', verbose_name='Часть')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='auth_app.profile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Товар в корзине',
                'verbose_name_plural': 'Товары в корзине',
            },
        ),
    ]
