# Generated by Django 5.2.7 on 2025-12-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catpart',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Доступно по умолчанию'),
        ),
    ]
